config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root :to => "home#index"

  resources :recipes, only: [:new, :create, :show, :update, :destroy, :edit]

end

app/views/partials/_navbar.html.erb
<nav class="navbar">
  <ul class="navlinks">
    <li class="navlink">
      <%= link_to "Home", root_url %>
    </li>

    <%# Removes the Login link if a user is not signed in %>
    <% unless current_user%>
      <li class="navlink">
      <%= link_to "Login", user_session_path %>
      <%end%>
      </li>

    <%# Creates a signout link if a user is not signed in %>
    <% if current_user %>
      <li class="navlink">
        <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }%>
      </li>
    <%end%>
  </ul>
</nav>

app/views/partials/_pagination_bar.erb
<div class="pagination-bar">
<% if @current_page > 1 %>
  <%= link_to image_tag('previous.svg', class: 'previous'), root_path(page: @current_page - 1, query: @params[:query]) %>
<% end %>
<% if total_pages < 10 %>
<% [*1..total_pages].each do |page| %>
  <%= link_to page, root_path(page: page, query: params[:query]), :class => "#{current_page == page ? 'active page-number' : 'page-number'}" %>
<%end%>
<% else %>
  <% [*1..total_pages].each do |page| %>
    <% if (current_page - page).abs() < 2 || (page - 1).abs() < 2 || (total_pages - page) < 2 %>
      <%= link_to page, root_path(page: page, query: params[:query]), :class => "#{current_page == page ? 'active page-number' : 'page-number'}" %>
    <% else %>
      <span>.</span>
    <% end %>
  <%end%>
<% end %>
<% if @current_page < total_pages %>
  <%= link_to image_tag('next.svg', class: 'next'), root_path(page: @current_page + 1, query: @params[:query]) %>
<% end %>
</div>
<br/>

app/views/partials/_recipe_full_view.html.erb
<section class="full-recipe-view">
  <article class="recipe">
    <% if recipe.image_data %>
    <%recipe.image_derivatives!%>
    <%= image_tag recipe.image_url(:large),:class => "recipe-image" %>
    <% end %>
    <div class="recipe-details">
      <h1 class="recipe-title"><%= recipe.name %></h1>
      <p class="recipe-description"><%= recipe.description %></p>
      <h2>Ingredients</h2>
      <div class="recipe-ingredients"><%= simple_format(recipe.ingredients) %></div>
      <h3>How to make</h3>
      <div class="recipe-directions"><%= simple_format(recipe.directions) %></div>
    </div>
  </article class="recipe">

  <%# renders buttons only if a user is logged in %>
  <%if current_user%>
  <div class="admin-buttons">
    <%=button_to 'Delete', recipe_path(recipe.id), method: :delete%>
    <%=button_to 'Edit', edit_recipe_path(recipe.id), method: :get%>
  </div>
  <%end%>
</section>

app/views/partials/_recipe_preview.html.erb
<a href=<%= recipe_path(recipe.id)%> class= "recipe-preview">
  <% if recipe.image_data%>
  <%recipe.image_derivatives!%>
  <%= image_tag recipe.image_url(:small)%>
  <%p recipe.image_data%>
  <% end %>
  <div class="preview-info">
    <p class="preview-name"><%=recipe.name%></p>
    <p class="preview-description"><%=recipe.description%></p>
  </div>
</a>