config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root :to => "home#index"

  resources :recipes, only: [:new, :create, :show, :update, :destroy, :edit]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # placeholder logic to prevent an endless user session.
  # Comment out before_action :signout if you want to stay logged in

  RECIPES_PER_PAGE = 4

  def index
    @recipes_all = Recipe.where('lower(name) LIKE ?', "%#{params[:query].to_s.downcase}%")
    @params = params.permit(:page, :query)
    @current_page = params[:page].to_i
    @current_page = 1 if @current_page.zero?
    @recipes = @recipes_all.offset((@current_page - 1) * RECIPES_PER_PAGE)
      .limit(RECIPES_PER_PAGE)
    @total_pages = (@recipes_all.count / RECIPES_PER_PAGE.to_f).ceil
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= render partial: 'partials/navbar'%>

<%= form_with url: root_path, class: "search-form", method: :get do %>
  <input class="search-bar" onkeydown="if(this.value == '') {this.name = 'query'} else {this.name = 'query'}" value=<%="#{@params[:query]}"%>>
  <%= image_submit_tag('search_icon.svg', name:nil, class:"search-icon") %>
<%end%>

<%
  @recipes.each do |recipe|
%>
<%= render partial: 'partials/recipe_preview', locals: { recipe: recipe }%>
<%end%>

<%= render partial: 'partials/pagination_bar', locals: { current_page: @current_page, total_pages: @total_pages, params: @params } %>

<% if current_user%>
<%= link_to "Create new recipe", new_recipe_path %>
<% end %>